services:
  - type: web
    name: news-spark
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://news-spark.onrender.com
      
      # ডাটাবেস কনফিগ
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.dmgsjqyoteglfyznjvvh.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: realpool55
      - key: DB_SCHEMA
        value: public
      - key: DB_SSL_MODE
        value: require
      
      # SSL সার্টিফিকেট কনফিগ
      - key: PGSSLMODE
        value: verify-full
      - key: PGSSLROOTCERT
        value: /etc/ssl/certs/ca-certificates.crt
      
      # ক্লাউডিনারি কনফিগ
      - key: CLOUDINARY_CLOUD_NAME
        value: dntcguitw
      - key: CLOUDINARY_API_KEY
        value: 687467651322471
      - key: CLOUDINARY_API_SECRET
        value: _StwvUBpt0Xq6-hB2YisBwGzDlA
      - key: CLOUDINARY_URL
        value: cloudinary://687467651322471:_StwvUBpt0Xq6-hB2YisBwGzDlA@dntcguitw
