services:
  - type: web
    name: news-spark-web
    env: docker
    dockerfilePath: ./Dockerfile
    # build command, if needed override: (Render uses Dockerfile)
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://news-spark.onrender.com  # আপনার বাস্তব ডোমেইন
      - key: DATABASE_URL
        fromDatabase: null  # আপনি Supabase এ থাকলে এখানে DIRECTLY ENV সেট করবেন Render UIতে
    # you won't put secrets here; set them in Render dashboard as secret vars

  - type: worker
    name: news-spark-queue
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: php artisan queue:work --sleep=3 --tries=3 --timeout=60
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"

  - type: cron
    name: news-spark-scheduler
    schedule: "*/5 * * * *" # প্রতি ৫ মিনিটে চালাবে
    command: php artisan schedule:run --verbose --no-interaction
    env:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
