services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "News Spark"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:S3cW7PzKnzVf07pUpSpqn2K5kSuX1njP1fFHsqlLeGg=
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: APP_MAINTENANCE_STORE
        value: database
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.dmgsjqyoteglfyznjvvh
      - key: DB_PASSWORD
        value: realpool55
      - key: DB_SCHEMA
        value: public
      - key: DB_SSL_MODE
        value: require
      - key: CLOUDINARY_CLOUD_NAME
        value: dntcguitw
      - key: CLOUDINARY_API_KEY
        value: 687467651322471
      - key: CLOUDINARY_API_SECRET
        value: _StwvUBpt0Xq6-hB2YisBwGzDlA
      - key: CLOUDINARY_URL
        value: cloudinary://687467651322471:_StwvUBpt0Xq6-hB2YisBwGzDlA@dntcguitw
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: CACHE_PREFIX
        value: ""
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_MAILER
        value: log
      - key: MAIL_HOST
        value: 127.0.0.1
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: News Spark
